#!/bin/bash

echo "<------------------>"
echo "1. Calc - defolt 4 functions calculator (func - sum, mul, sub, div) witch takes 2 int numbers as arg"
echo "2. Search - recursive search through file in the directory (arg - directory, exeption)"
echo "3. Reverse - invented entry from one file to another (arg - file, file)"
echo "4. Strlen - output the number of cheracters in a string (arg - string)"
echo "5. Log - print wornings and information massages from /var/log/anaconda/X.log"
echo "6. Exit - exit from script with specified code (arg - int nuber(default is 0))"
echo "7. Interactive - active interactive mode"
echo "<------------------>"
echo "All exit code:"
echo "No argument found - exit -2"
echo "Incorrct type - exit -3"
echo "Zero dividing - exit -4"
echo "Cant find directory - exit -5"
echo "Argument is not a file - exit -6"
echo "Not readeble file - exit -7"
echo "Exit code is no a number - exit -8"
echo "<------------------>"
